authors/urls.py
from django.urls import path
from . import views
app_name = 'authors'

urlpatterns = [
    path('register/',views.register_view,name='register'),
    path('register/create/',views.register_create,name='create'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('recipes.urls')),
    path('authors/', include('authors.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('recipes.urls'))

]

recipes/urls.py
from django.urls import path
from recipes import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home,name="home"),
    path('recipes/search/', views.search,name="search"),

    path('recipes/category/<int:category_id>/', views.category,name="category"),

    path('recipes/<int:id>/', views.recipe,name="recipe"),


]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name



class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True) #cria uma data no momento da criação
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

authors/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class RegisterForm(forms.ModelForm):
    password2 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'placeholder':'Repeat your password'}),
                                error_messages={
                                    'password2': {
                                        'required': 'password must not be empty',

                                    }
                                }

                                )


    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password',
                  ]
        labels = {
            'username':'Username',
            'first_name':'First name',
            'last_name':'Last name',
            'email':'Email',
            'password':'Password',
        }
        help_texts = {
            'email':'The E-mail must be valid.',
            'password':'Password must have at least one uppercase letter,one lowercase letter and one number.the length should be at'
                                           'least 8 characters'
        }
        error_messages = {
            'first_name': {
                'required': 'This field must not be empty in first_name',
            },
            'last_name': {
                'required': 'This field must not be empty in first_name',
            },
            'username':{
                'required':'This field must not be empty',
                'max_length':'This field must have less than 3 characters',

            }
        }
        widgets = {
            'first_name':forms.TextInput(attrs={'placeholder':'Ex.:John'}),
            'password':forms.PasswordInput(attrs={'placeholder':'Type your password here'}),
            'username': forms.TextInput(attrs={'placeholder': 'Your username'}),
            'email': forms.TextInput(attrs={'placeholder': 'Your E-mail'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Ex.:Lola'}),
        }



    def clean_password(self):
        data = self.cleaned_data.get('password')
        if 'atenção' in data:
            raise ValidationError('não digite %(pipoca)s , Valor invalido',code='invalid',
                                  params={'pipoca':'"atenção"'})

        return data

    def clean_email(self):
        email = self.cleaned_data.get('email')
        exists = User.objects.filter(email=email).exists()
        if exists :
            raise ValidationError('User E-mail is already in use ', code='invalid',)

        return email


    def clean_first_name(self):
        data = self.cleaned_data.get('first_name')
        if not data :
            raise ValidationError('This field must not be empty in first name',code='invalid',)

        return data

    def clean_last_name(self):
        data = self.cleaned_data.get('last_name')
        if not data:
            raise ValidationError('This field must not be empty in last name', code='invalid',)

        return data

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            raise ValidationError({
                'password':'Password and Password 2 must be equal'
            })

recipes/views.py
import os

from django.shortcuts import render, get_list_or_404 , get_object_or_404
from django.http.response import Http404
from django.db.models import Q
from recipes.models import Recipe
from utils.recipes.paginations import make_pagination
from django.contrib import messages

PER_PAGES = int(os.environ.get('PER_PAGE',6))
# Create your views here.
def home(request):
    recipes = get_list_or_404(Recipe.objects.filter(is_published=True).order_by('-id'))

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)


    return render(request,'pages/home.html',context={'recipes': page_obj,'pagination_range':pagination_range})

def category(request,category_id):


    recipes = get_list_or_404(Recipe.objects.filter(category__id=category_id,is_published=True ).order_by('-id'))
    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)

    return render(request,'pages/category.html',context={'recipes': page_obj,
        'pagination_range': pagination_range,'title':f'{recipes[0].category.name} - Category |'
})


def recipe(request, id):
    recipe = get_object_or_404(Recipe, id=id, is_published=True,)
    return render(request,'pages/recipe-view.html',context={'recipe':recipe,'is_detail_page':True,})

def search(request):
    search_term = request.GET.get('q','').strip()

    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
        ),
        is_published=True
    ).order_by('-id')
    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)

    return render(request,'pages/search.html',context={'page_title':f'Search for "{search_term}" |','search_term':search_term,
                                                       'recipes': page_obj,
                                                       'pagination_range': pagination_range,
                                                       'additional_url_query': f'&q={search_term}',
                                                       })

authors/templates/author/pages/register_view.html
{% extends 'global/base.html' %}

{% block title %}Register | {% endblock title %}

{% block content %}
   <div class="main-content center container">
       <h2>REGISTER</h2>
   </div>
   {% include 'global/partials/message.html' %}
   <div class="main-content container">
       <form action="{% url 'authors:create'%}" method="post">
           {% csrf_token %}
           <div class="form-content form-content-grid">
               {% for field in form  %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}

                        {% if field.help_text %}
                         <p class="help-text">{{ field.help_text }}</p>
                        {% endif %}

                        {{ field.errors }}
                    </div>
               {% endfor %}
           </div>
           <div class="form-content form-content-grid">
               <div class="form-group">
                   <button type="submit"> Send </button>
               </div>
           </div>
           {% if form.errors %}
               <div class="form-content form-content-grid">
                 <div class="form-group">
                   <div class="message message-error">
                        There are errors in the form, please fix them and send again.
                   </div>
                 </div>
               </div>
           {% endif %}
       </form>
   </div>
{% endblock content %}

recipes/templates/pages/category.html
{% extends 'global/base.html' %}

{% block title %} {{ title }}  {% endblock title %}

{% block content %}

    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipes.html' %}
        {% endfor %}

    </div>
{% endblock content %}

recipes/templates/pages/home.html
{% extends 'global/base.html' %}

{% block title %} HOME {% endblock title %}

{% block content %}
    {% include 'global/partials/message.html' %}

    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipes.html' %}
        {% endfor %}

    </div>
{% endblock content %}

recipes/templates/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %} {{ recipe.title }} {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% if recipe  %}
        {% include 'recipes/partials/recipes.html' %}
    {% endif %}

</div>
{% endblock content %}

recipes/templates/pages/search.html
{% extends 'global/base.html' %}

{% block title %} {{ page_title }} Recipes {% endblock title %}

{% block content %}

    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipes.html' %}
        {% endfor %}

    </div>
{% endblock content %}

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/fontawesome.min.css" integrity="sha512-siarrzI1u3pCqFG2LEzi87McrBmq6Tp7juVsdmGY1Dr8Saw+ZBAzDzrGwX3vgxX1NkioYNCFOVC0GpDPss10zQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/brands.min.css" integrity="sha512-W/zrbCncQnky/EzL+/AYwTtosvrM+YG/V6piQLSe2HuKS6cmbw89kjYkp3tWFn1dkWV7L1ruvJyKbLz73Vlgfg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/solid.min.css"
          integrity="sha512-P9pgMgcSNlLb4Z2WAB2sH5KBKGnBfyJnq+bhcfLCFusrRc4XdXrhfDluBl/usq75NF5gTDIMcwI1GaG5gju+Mw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link  rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
    <link  rel="stylesheet" href="{% static 'global/css/global-style.css' %}">

recipes/templates/recipes/partials/recipes.html
 <div class="recipe recipe-list-item">
     {% if recipe.cover.url is not Null %}
                    <div class="recipe-cover">
                        <a href="{% url 'recipes:recipe' recipe.id %}">
                            <img src="{{ recipe.cover.url }}" alt="Temporário">
                        </a>

                    </div>
     {% endif %}

                    <div class="recipe-title-container">
                        <h2 class="recipe-title">
                            <a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe.title }}</a>
                        </h2>
                    </div>

                 <div class="recipe-author">

                            <span class="recipe-author-item">
                                <i class="fas fa-user"></i>
                                 {% if recipe.author is not None %}
                                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                                 {% else %}
                                    Desconhecido
                                {% endif %}
                            </span>
                            <span class="recipe-author-item">
                                <i class="fas fa-calendar-alt"></i>
                                {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}

                            </span>



                       {% if recipe.category is not None %}
                                <span class="recipe-author-item">
                                    <a href="{% url 'recipes:category' recipe.category.id %}">
                                        <i class="fas fa-layer-group"></i>
                                        <span>{{ recipe.category.name }}</span>
                                    </a>
                                </span>
                     {% endif %}
                </div>
                <div class="recipe-content">
                        <p>{{ recipe.description }}</p>
                </div>

                 <div class="recipe-meta-container">
                    <div class="recipe-meta recipe-preparation">
                        <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
                        <div class="recipe-meta-text">
                             {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
                        </div>
                    </div>
                    <div class="recipe-meta recipe-servings">
                        <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
                        <div class="recipe-meta-text">

                            {{ recipe.servings }} {{ recipe.servings_unit }}
                        </div>
                    </div>
                </div>
              {% if is_detail_page is not True %}
                <footer class="recipe-footer">
                <a  href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark button-full-width">
                    <i class="fas fa-eye"></i>
                    <span>ver mais...</span>
                </a>
                </footer>
              {% endif %}
              {% if is_detail_page is  True %}
                 <div class="preparation-steps">
                     {% if recipe.preparation_steps_is_html is True %}
                        {{ recipe.preparation_steps|safe }}
                    {% else %}
                        {{ recipe.preparation_steps|linebreaksbr }}
                     {% endif %}
                 </div>

              {% endif %}

       </div>